import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsString, IsOptional, IsArray, ValidateNested, IsEnum, IsObject } from 'class-validator';

/**
 * Work type enumeration
 */
export enum WorkTypeEnum {
    Movie = 'movie',
    Episode = 'episode',
    Promotion = 'promotion',
    Season = 'season',
    Series = 'series',
}

/**
 * Release type enumeration
 */
export enum ReleaseTypeEnum {
    Original = 'Original',
    Broadcast = 'Broadcast',
    DVD = 'DVD',
    BluRay = 'Blu-ray',
    PayTV = 'PayTV',
    InternetBuy = 'InternetBuy',
    InternetRent = 'InternetRent',
    Theatrical = 'Theatrical',
    SVOD = 'SVOD',
}

/**
 * Identifier namespace enumeration
 */
export enum NamespaceTypeEnum {
    EIDR = 'EIDR',
    ISAN = 'ISAN',
    IMDB = 'IMDB',
    ORG = 'ORG',
}

/**
 * Category type enumeration
 */
export enum CategoryEnum {
    Episode = 'Episode',
    Feature = 'Feature',
    Season = 'Season',
    Series = 'Series',
    Promotion = 'Promotion',
}

/**
 * Art reference (images, posters, etc.)
 */
export class ArtReferenceDto {
    @ApiProperty({
        example: 'https://s3.amazonaws.com/bucket/images/cover.jpg',
        description: 'Image file URL or path',
    })
    @IsString()
    reference: string;

    @ApiProperty({ example: '1920x1080', description: 'Image resolution (e.g., 1920x1080, 4:3)' })
    @IsString()
    resolution: string;

    @ApiProperty({ example: 'cover', description: 'Image purpose (e.g., cover, hero, boxart)' })
    @IsString()
    purpose: string;
}

/**
 * Localized information for a specific language
 */
export class LocalizedInfoDto {
    @ApiProperty({ example: 'en-US', description: 'Language code (RFC 5646)' })
    @IsString()
    language: string;

    @ApiProperty({ example: 'The Matrix', description: 'Display title' })
    @IsString()
    titleDisplay: string;

    @ApiPropertyOptional({
        example: 'Matrix',
        description: 'Sort title - OPTIONAL: Auto-generated by removing articles (The, A, An) if not provided',
    })
    @IsOptional()
    @IsString()
    titleSort?: string;

    @ApiPropertyOptional({
        example: 'A computer hacker learns about the true nature of his reality.',
        description: 'Short summary (max 190 characters)',
        maxLength: 190,
    })
    @IsOptional()
    @IsString()
    summary190?: string;

    @ApiPropertyOptional({
        example:
            'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        description: 'Long summary (max 400 characters)',
        maxLength: 400,
    })
    @IsOptional()
    @IsString()
    summary400?: string;

    @ApiPropertyOptional({
        type: [ArtReferenceDto],
        description: 'Art references (images, posters, etc.)',
    })
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => ArtReferenceDto)
    artReference?: ArtReferenceDto[];
}

/**
 * Genre classification
 */
export class GenreDto {
    @ApiProperty({
        example: 'Action',
        description: 'Primary genre (e.g., Action, Drama, Comedy)',
    })
    @IsString()
    primary: string;

    @ApiPropertyOptional({
        type: [String],
        example: ['Adventure', 'Thriller'],
        description: 'Sub-genres (max 3 total genres including primary)',
    })
    @IsOptional()
    @IsArray()
    @IsString({ each: true })
    subGenre?: string[];
}

/**
 * Release history entry
 */
export class ReleaseHistoryDto {
    @ApiProperty({
        enum: ReleaseTypeEnum,
        example: ReleaseTypeEnum.Original,
        description: 'Release type',
    })
    @IsEnum(ReleaseTypeEnum)
    type: ReleaseTypeEnum;

    @ApiProperty({ example: 'US', description: 'Release country code (ISO 3166-1 alpha-2)' })
    @IsString()
    country: string;

    @ApiProperty({ example: '1999-03-31', description: 'Release date (YYYY-MM-DD)' })
    @IsString()
    date: string;
}

/**
 * Content identifier (EIDR, ISAN, IMDB, etc.)
 */
export class ContentIdentifierDto {
    @ApiProperty({
        enum: NamespaceTypeEnum,
        example: NamespaceTypeEnum.ORG,
        description: 'Identifier namespace',
    })
    @IsEnum(NamespaceTypeEnum)
    namespace: NamespaceTypeEnum;

    @ApiProperty({
        example: 'wiflix-matrix-001',
        description: 'Identifier value',
    })
    @IsString()
    value: string;
}

/**
 * Content rating
 */
export class RatingDto {
    @ApiProperty({ example: 'US', description: 'Rating country code (ISO 3166-1 alpha-2)' })
    @IsString()
    country: string;

    @ApiProperty({ example: 'MPAA', description: 'Rating system (e.g., MPAA, BBFC, FSK)' })
    @IsString()
    system: string;

    @ApiProperty({ example: 'R', description: 'Rating value (e.g., R, PG-13, 18)' })
    @IsString()
    value: string;
}

/**
 * Cast or crew member
 */
export class CastMemberDto {
    @ApiProperty({
        example: 'Actor',
        description: 'Job function (e.g., Actor, Director, Producer)',
    })
    @IsString()
    jobFunction: string;

    @ApiProperty({ example: '1', description: 'Billing order for credits' })
    @IsString()
    billingBlockOrder: string;

    @ApiProperty({
        type: Object,
        example: { 'en-US': 'Keanu Reeves', 'ja-JP': 'キアヌ・リーブス' },
        description: 'Display names in different languages (language code -> name mapping)',
    })
    @IsObject()
    displayName: Record<string, string>;
}

/**
 * Organization information
 */
export class OrganizationDto {
    @ApiProperty({
        example: 'md:orgid:wiflix',
        description: 'Organization identifier',
    })
    @IsString()
    id: string;

    @ApiProperty({
        example: 'licensor',
        description: 'Organization role (typically "licensor" for Amazon Prime)',
    })
    @IsString()
    role: string;
}

/**
 * Company display credit
 */
export class CompanyCreditDto {
    @ApiProperty({ example: 'WiFlix Studios', description: 'Company credit text' })
    @IsString()
    value: string;

    @ApiProperty({ example: 'en-US', description: 'Language code for the credit' })
    @IsString()
    language: string;
}

/**
 * Category information (for episodic content)
 */
export class CategoryInfoDto {
    @ApiProperty({
        enum: CategoryEnum,
        example: CategoryEnum.Episode,
        description: 'Category type',
    })
    @IsEnum(CategoryEnum)
    type: CategoryEnum;

    @ApiPropertyOptional({
        example: '1',
        description: 'Sequence number (for episodes/seasons)',
    })
    @IsOptional()
    @IsString()
    sequenceNumber?: string;

    @ApiPropertyOptional({
        example: 'md:cid:org:wiflix:series-name',
        description: 'Parent content ID (for episodes linking to seasons/series)',
    })
    @IsOptional()
    @IsString()
    parentContentId?: string;
}

/**
 * Complete MEC (Media Entertainment Core) data structure for XML generation
 *
 * **MEC contains metadata about your content:**
 * - Title, cast, genres, ratings, release dates
 * - Localized information for multiple languages
 * - Company credits and organization details
 *
 * **REQUIRED FIELDS:**
 * - contentId: MovieLabs content identifier (format: md:cid:org:{organization}:{content-slug})
 * - localizedInfo: At least one entry with language, titleDisplay, summary400
 * - genre: At least one primary genre (max 3 total including sub-genres)
 * - releaseYear: Year of release (YYYY)
 * - releaseDate: Full date (YYYY-MM-DD)
 * - releaseHistory: At least one release entry (type, country, date)
 * - workType: movie, episode, season, series, promotion
 * - identifier: At least one identifier (namespace, value)
 * - cast: At least one cast/crew member
 * - originalLanguage: Original content language (ISO 639-1)
 * - organization: Organization info (id, role)
 * - companyDisplayCredit: Company credit (value, language)
 *
 * **OPTIONAL FIELDS:**
 * - rating: Content ratings (MPAA, BBFC, etc.)
 * - category: For episodic content (Episode, Season, Series)
 *
 * **AUTO-GENERATED FIELDS:**
 * - titleSort: Auto-generated from titleDisplay by removing articles (The, A, An)
 *   Example: "The Matrix" → "Matrix", "A Beautiful Mind" → "Beautiful Mind"
 *
 * **CONTENT ID FORMAT:**
 * Must follow MovieLabs specification:
 * - Movie: md:cid:org:yourorg:movie-slug
 * - Episode: md:cid:org:yourorg:series-slug:s01:e03
 * - Season: md:cid:org:yourorg:series-slug:s01
 * - Series: md:cid:org:yourorg:series-slug
 *
 * **MULTI-LANGUAGE SUPPORT:**
 * Add multiple localizedInfo entries for different languages.
 * Each can have its own title, summaries, and artwork.
 */
export class GenerateMECDto {
    @ApiPropertyOptional({
        example: 'md:cid:org:wiflix:the-matrix',
        description:
            '**OPTIONAL** - Unique content identifier in MovieLabs format. If not provided, will be auto-generated from organization + title. Format: md:cid:org:{organization}:{content-slug}. For episodes: md:cid:org:{org}:{series}:s{season}:e{episode}',
        required: false,
    })
    @IsOptional()
    @IsString()
    contentId?: string;

    @ApiProperty({
        type: [LocalizedInfoDto],
        description:
            '**REQUIRED** - Localized information for different languages (at least 1). Each entry requires: language, titleDisplay. titleSort is auto-generated by removing articles.',
        required: true,
        isArray: true,
        minItems: 1,
        example: [
            {
                language: 'en-US',
                titleDisplay: 'The Matrix',
                summary400: 'A computer hacker learns about the true nature of reality.',
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => LocalizedInfoDto)
    localizedInfo: LocalizedInfoDto[];

    @ApiProperty({
        type: [GenreDto],
        description:
            '**REQUIRED** - Genre classifications (at least 1). Maximum 3 total genres including primary + sub-genres. Common genres: Action, Drama, Comedy, Horror, Romance, Thriller, Sci-Fi',
        required: true,
        isArray: true,
        minItems: 1,
        maxItems: 3,
        example: [{ primary: 'Action', subGenre: ['Sci-Fi', 'Thriller'] }],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => GenreDto)
    genre: GenreDto[];

    @ApiProperty({
        example: '1999',
        description: '**REQUIRED** - Release year in YYYY format (e.g., 2024, 1999)',
        required: true,
    })
    @IsString()
    releaseYear: string;

    @ApiProperty({
        example: '1999-03-31',
        description: '**REQUIRED** - Full release date in YYYY-MM-DD format (e.g., 2024-01-15)',
        required: true,
    })
    @IsString()
    releaseDate: string;

    @ApiProperty({
        type: [ReleaseHistoryDto],
        description:
            '**REQUIRED** - Release history across territories and platforms (at least 1). Each entry requires: type (Original, Theatrical, SVOD, etc.), country (ISO 3166-1 alpha-2), date',
        required: true,
        isArray: true,
        minItems: 1,
        example: [
            {
                type: 'Theatrical',
                country: 'US',
                date: '1999-03-31',
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => ReleaseHistoryDto)
    releaseHistory: ReleaseHistoryDto[];

    @ApiProperty({
        enum: WorkTypeEnum,
        example: WorkTypeEnum.Movie,
        description: '**REQUIRED** - Type of work. Values: movie, episode, season, series, promotion',
        required: true,
    })
    @IsEnum(WorkTypeEnum)
    workType: WorkTypeEnum;

    @ApiProperty({
        type: [ContentIdentifierDto],
        description:
            '**REQUIRED** - Alternative identifiers (at least 1). Common namespaces: ORG (organization-specific), IMDB, EIDR, ISAN. Each requires: namespace, value',
        required: true,
        isArray: true,
        minItems: 1,
        example: [
            {
                namespace: 'ORG',
                value: 'wiflix-matrix-001',
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => ContentIdentifierDto)
    identifier: ContentIdentifierDto[];

    @ApiPropertyOptional({
        type: [RatingDto],
        description:
            '**OPTIONAL** - Content ratings for different territories. Common systems: MPAA (US), BBFC (UK), FSK (Germany), EIRIN (Japan). Each requires: country, system, value',
        required: false,
        isArray: true,
    })
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => RatingDto)
    rating?: RatingDto[];

    @ApiProperty({
        type: [CastMemberDto],
        description: 'Cast and crew members',
        example: [
            {
                jobFunction: 'Actor',
                billingBlockOrder: '1',
                displayName: { 'en-US': 'Keanu Reeves' },
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => CastMemberDto)
    cast: CastMemberDto[];

    @ApiProperty({
        example: 'en',
        description: 'Original language of the content (ISO 639-1)',
    })
    @IsString()
    originalLanguage: string;

    @ApiProperty({
        type: OrganizationDto,
        description: 'Associated organization information',
        example: {
            id: 'md:orgid:wiflix',
            role: 'licensor',
        },
    })
    @ValidateNested()
    @Type(() => OrganizationDto)
    organization: OrganizationDto;

    @ApiProperty({
        type: CompanyCreditDto,
        description: 'Company display credit information',
        example: {
            value: 'WiFlix Studios',
            language: 'en-US',
        },
    })
    @ValidateNested()
    @Type(() => CompanyCreditDto)
    companyDisplayCredit: CompanyCreditDto;

    @ApiPropertyOptional({
        type: CategoryInfoDto,
        description: 'Category information (required for episodic content)',
    })
    @IsOptional()
    @ValidateNested()
    @Type(() => CategoryInfoDto)
    category?: CategoryInfoDto;
}
