import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsString, IsOptional, IsArray, ValidateNested, IsEnum, IsObject } from 'class-validator';

/**
 * Work type enumeration
 */
export enum WorkTypeEnum {
    Movie = 'movie',
    Episode = 'episode',
    Promotion = 'promotion',
    Season = 'season',
    Series = 'series',
}

/**
 * Release type enumeration
 */
export enum ReleaseTypeEnum {
    Original = 'Original',
    Broadcast = 'Broadcast',
    DVD = 'DVD',
    BluRay = 'Blu-ray',
    PayTV = 'PayTV',
    InternetBuy = 'InternetBuy',
    InternetRent = 'InternetRent',
    Theatrical = 'Theatrical',
    SVOD = 'SVOD',
}

/**
 * Identifier namespace enumeration
 */
export enum NamespaceTypeEnum {
    EIDR = 'EIDR',
    ISAN = 'ISAN',
    IMDB = 'IMDB',
    ORG = 'ORG',
}

/**
 * Category type enumeration
 */
export enum CategoryEnum {
    Episode = 'Episode',
    Feature = 'Feature',
    Season = 'Season',
    Series = 'Series',
    Promotion = 'Promotion',
}

/**
 * Art reference (images, posters, etc.)
 */
export class ArtReferenceDto {
    @ApiProperty({
        example: 'https://s3.amazonaws.com/bucket/images/cover.jpg',
        description: 'Image file URL or path',
    })
    @IsString()
    reference: string;

    @ApiProperty({ example: '1920x1080', description: 'Image resolution (e.g., 1920x1080, 4:3)' })
    @IsString()
    resolution: string;

    @ApiProperty({ example: 'cover', description: 'Image purpose (e.g., cover, hero, boxart)' })
    @IsString()
    purpose: string;
}

/**
 * Localized information for a specific language
 */
export class LocalizedInfoDto {
    @ApiProperty({ example: 'en-US', description: 'Language code (RFC 5646)' })
    @IsString()
    language: string;

    @ApiProperty({ example: 'The Matrix', description: 'Display title' })
    @IsString()
    titleDisplay: string;

    @ApiPropertyOptional({
        example: 'Matrix',
        description: 'Sort title - OPTIONAL: Auto-generated by removing articles (The, A, An) if not provided',
    })
    @IsOptional()
    @IsString()
    titleSort?: string;

    @ApiPropertyOptional({
        example: 'A computer hacker learns about the true nature of his reality.',
        description: 'Short summary (max 190 characters)',
        maxLength: 190,
    })
    @IsOptional()
    @IsString()
    summary190?: string;

    @ApiPropertyOptional({
        example:
            'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        description: 'Long summary (max 400 characters)',
        maxLength: 400,
    })
    @IsOptional()
    @IsString()
    summary400?: string;

    @ApiPropertyOptional({
        type: [ArtReferenceDto],
        description: 'Art references (images, posters, etc.)',
    })
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => ArtReferenceDto)
    artReference?: ArtReferenceDto[];
}

/**
 * Genre classification
 */
export class GenreDto {
    @ApiProperty({
        example: 'Action',
        description: 'Primary genre (e.g., Action, Drama, Comedy)',
    })
    @IsString()
    primary: string;

    @ApiPropertyOptional({
        type: [String],
        example: ['Adventure', 'Thriller'],
        description: 'Sub-genres (max 3 total genres including primary)',
    })
    @IsOptional()
    @IsArray()
    @IsString({ each: true })
    subGenre?: string[];
}

/**
 * Release history entry
 */
export class ReleaseHistoryDto {
    @ApiProperty({
        enum: ReleaseTypeEnum,
        example: ReleaseTypeEnum.Original,
        description: 'Release type',
    })
    @IsEnum(ReleaseTypeEnum)
    type: ReleaseTypeEnum;

    @ApiProperty({ example: 'US', description: 'Release country code (ISO 3166-1 alpha-2)' })
    @IsString()
    country: string;

    @ApiProperty({ example: '1999-03-31', description: 'Release date (YYYY-MM-DD)' })
    @IsString()
    date: string;
}

/**
 * Content identifier (EIDR, ISAN, IMDB, etc.)
 */
export class ContentIdentifierDto {
    @ApiProperty({
        enum: NamespaceTypeEnum,
        example: NamespaceTypeEnum.ORG,
        description: 'Identifier namespace',
    })
    @IsEnum(NamespaceTypeEnum)
    namespace: NamespaceTypeEnum;

    @ApiProperty({
        example: 'wiflix-matrix-001',
        description: 'Identifier value',
    })
    @IsString()
    value: string;
}

/**
 * Content rating
 */
export class RatingDto {
    @ApiProperty({ example: 'US', description: 'Rating country code (ISO 3166-1 alpha-2)' })
    @IsString()
    country: string;

    @ApiProperty({ example: 'MPAA', description: 'Rating system (e.g., MPAA, BBFC, FSK)' })
    @IsString()
    system: string;

    @ApiProperty({ example: 'R', description: 'Rating value (e.g., R, PG-13, 18)' })
    @IsString()
    value: string;
}

/**
 * Cast or crew member
 */
export class CastMemberDto {
    @ApiProperty({
        example: 'Actor',
        description: 'Job function (e.g., Actor, Director, Producer)',
    })
    @IsString()
    jobFunction: string;

    @ApiProperty({ example: '1', description: 'Billing order for credits' })
    @IsString()
    billingBlockOrder: string;

    @ApiProperty({
        type: Object,
        example: { 'en-US': 'Keanu Reeves', 'ja-JP': 'キアヌ・リーブス' },
        description: 'Display names in different languages (language code -> name mapping)',
    })
    @IsObject()
    displayName: Record<string, string>;
}

/**
 * Organization information
 */
export class OrganizationDto {
    @ApiProperty({
        example: 'md:orgid:wiflix',
        description: 'Organization identifier',
    })
    @IsString()
    id: string;

    @ApiProperty({
        example: 'licensor',
        description: 'Organization role (typically "licensor" for Amazon Prime)',
    })
    @IsString()
    role: string;
}

/**
 * Company display credit
 */
export class CompanyCreditDto {
    @ApiProperty({ example: 'WiFlix Studios', description: 'Company credit text' })
    @IsString()
    value: string;

    @ApiProperty({ example: 'en-US', description: 'Language code for the credit' })
    @IsString()
    language: string;
}

/**
 * Category information (for episodic content)
 */
export class CategoryInfoDto {
    @ApiProperty({
        enum: CategoryEnum,
        example: CategoryEnum.Episode,
        description: 'Category type',
    })
    @IsEnum(CategoryEnum)
    type: CategoryEnum;

    @ApiPropertyOptional({
        example: '1',
        description: 'Sequence number (for episodes/seasons)',
    })
    @IsOptional()
    @IsString()
    sequenceNumber?: string;

    @ApiPropertyOptional({
        example: 'md:cid:org:wiflix:series-name',
        description: 'Parent content ID (for episodes linking to seasons/series)',
    })
    @IsOptional()
    @IsString()
    parentContentId?: string;
}

/**
 * Complete MEC (Media Entertainment Core) data structure
 */
export class GenerateMECDto {
    @ApiProperty({
        example: 'md:cid:org:wiflix:the-matrix',
        description: 'Unique content identifier (MovieLabs ID format)',
    })
    @IsString()
    contentId: string;

    @ApiProperty({
        type: [LocalizedInfoDto],
        description: 'Localized information for different languages (at least one required)',
        example: [
            {
                language: 'en-US',
                titleDisplay: 'The Matrix',
                summary400: 'A computer hacker learns about the true nature of reality.',
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => LocalizedInfoDto)
    localizedInfo: LocalizedInfoDto[];

    @ApiProperty({
        type: [GenreDto],
        description: 'Genre classifications (max 3 total including sub-genres)',
        example: [{ primary: 'Action', subGenre: ['Sci-Fi', 'Thriller'] }],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => GenreDto)
    genre: GenreDto[];

    @ApiProperty({
        example: '1999',
        description: 'Release year (YYYY format)',
    })
    @IsString()
    releaseYear: string;

    @ApiProperty({
        example: '1999-03-31',
        description: 'Full release date (YYYY-MM-DD format)',
    })
    @IsString()
    releaseDate: string;

    @ApiProperty({
        type: [ReleaseHistoryDto],
        description: 'Release history across territories and platforms',
        example: [
            {
                type: 'Theatrical',
                country: 'US',
                date: '1999-03-31',
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => ReleaseHistoryDto)
    releaseHistory: ReleaseHistoryDto[];

    @ApiProperty({
        enum: WorkTypeEnum,
        example: WorkTypeEnum.Movie,
        description: 'Type of work',
    })
    @IsEnum(WorkTypeEnum)
    workType: WorkTypeEnum;

    @ApiProperty({
        type: [ContentIdentifierDto],
        description: 'Alternative identifiers (EIDR, ISAN, IMDB, etc.)',
        example: [
            {
                namespace: 'ORG',
                value: 'wiflix-matrix-001',
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => ContentIdentifierDto)
    identifier: ContentIdentifierDto[];

    @ApiPropertyOptional({
        type: [RatingDto],
        description: 'Content ratings (optional)',
    })
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => RatingDto)
    rating?: RatingDto[];

    @ApiProperty({
        type: [CastMemberDto],
        description: 'Cast and crew members',
        example: [
            {
                jobFunction: 'Actor',
                billingBlockOrder: '1',
                displayName: { 'en-US': 'Keanu Reeves' },
            },
        ],
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => CastMemberDto)
    cast: CastMemberDto[];

    @ApiProperty({
        example: 'en',
        description: 'Original language of the content (ISO 639-1)',
    })
    @IsString()
    originalLanguage: string;

    @ApiProperty({
        type: OrganizationDto,
        description: 'Associated organization information',
        example: {
            id: 'md:orgid:wiflix',
            role: 'licensor',
        },
    })
    @ValidateNested()
    @Type(() => OrganizationDto)
    organization: OrganizationDto;

    @ApiProperty({
        type: CompanyCreditDto,
        description: 'Company display credit information',
        example: {
            value: 'WiFlix Studios',
            language: 'en-US',
        },
    })
    @ValidateNested()
    @Type(() => CompanyCreditDto)
    companyDisplayCredit: CompanyCreditDto;

    @ApiPropertyOptional({
        type: CategoryInfoDto,
        description: 'Category information (required for episodic content)',
    })
    @IsOptional()
    @ValidateNested()
    @Type(() => CategoryInfoDto)
    category?: CategoryInfoDto;
}
